name: PromotionsPlus
version: 2.0
author: GrayoneJr
main: com.civitasmc.promotionsplus.Main
description: PromotionsPlus - A promotion plugin!

commands:
  promotionsboard:
   aliases: [pb]
   description: Open the Promotions Borad.
  promote:
   aliases: [promo]
   description: Open the Promotion Settings pannel.
  ppreload:
   aliases: [pprl]
   description: Reload the whole plugin.
  pphelp:
   aliases: [ph]
   description: Help command..
  buttscmd:
   aliases: [butt]
   description: Yaas..